- name: Install flatpak
  become: yes
  package:
    name:
      - flatpak
    state: latest

- name: Add flathub remote
  become: "{{ flatpak_needs_root }}"
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  become: "{{ flatpak_needs_root }}"
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.calibre_ebook.calibre
      - com.discordapp.Discord
      - com.github.johnfactotum.Foliate
      - com.github.tchx84.Flatseal
      - com.nextcloud.desktopclient.nextcloud
      - com.obsproject.Studio
      - com.spotify.Client
      - de.haeckerfelix.Shortwave
      - im.riot.Riot
      - md.obsidian.Obsidian
      - org.blender.Blender
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.telegram.desktop
    state: present
    remote: flathub
