---
- name: Create .fonts directory
  file:
    path: ~/.fonts
    state: directory

- name: Install FiraCode Nerd Font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: ~/.fonts
    remote_src: yes
