---
- name: Distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Ansible community collections
  shell: "ansible-galaxy collection install community.general"

- name: Install packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ system_packages }}"

- name: Setup virtualization
  include_tasks: virtualization.yml

- name: Setup flatpaks
  include_tasks: flatpaks.yml

- name: Setup fonts
  include_tasks: fonts.yml
