---
- name: Distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Setup virtualization
  include_tasks: virtualization.yml

- name: Setup flatpaks
  include_tasks: flatpaks.yml
