---
- name: Distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Ansible community collections
  shell: "ansible-galaxy collection install community.general"

- name: Install packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ system_packages }}"

- name: Setup virtualization
  include_tasks: virtualization.yml

- name: Setup Flatpaks
  include_tasks: flatpaks.yml

- name: Setup fonts
  include_tasks: fonts.yml

- name: Setup icons
  include_tasks: icons.yml

    # - name: Setup Visual Studio Code
    # include_tasks: vscode.yml
    #
    # - name: Apply KDE configuration
    # include_tasks: kde.yml
