---
- name: Install libvirt
  become: yes
  package:
    name:
      - libvirt
      - virt-manager
    state: latest

- name: Add user to 'libvirt' group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - libvirt

- name: Enable and start 'libvirtd' service
  become: yes
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: Install vagrant
  become: yes
  package:
    name:
      - vagrant
    state: latest
