---
- name: Install Rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "~/.cargo/bin/rustup"
    executable: /bin/bash

- name: Install Cargo dependencies
  become: yes
  package:
    name: "{{ cargo_dep }}"
    state: latest
  with_items: "{{ cargo_deps }}"
  loop_control:
    loop_var: cargo_dep

- name: Build and install Cargo packages
  become: no
  shell: 'source ~/.cargo/env; cargo install --list | grep -q {{ cargo_package }} || cargo install {{ cargo_package }}'
  with_items: "{{ cargo_packages }}"
  loop_control:
    loop_var: cargo_package

- name: Update Cargo packages
  shell: cargo install-update -a
