- name: "Clone dotfiles repository"
  git:
    repo: https://github.com/trmckay/dotfiles.git
    dest: ~/.dotfiles
    clone: yes
    update: no
    remote: https

- name: "Configure dotfiles remote"
  git:
    repo: git@github.com:trmckay/dotfiles.git
    remote: origin
    dest: ~/.dotfiles
    clone: no
    update: no

- name: "Link dotfiles"
  command:
    cmd: "python3 ./link.py"
    chdir: ~/.dotfiles

- name: Download fzf key-bindings
  get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh
    dest: ~/.fzf.zsh
    mode: 0660

- name: Install vim-plug for Neovim
  shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    executable: /bin/bash
    creates: ~/.local/share/nvim/site/autoload/plug.vim

- name: Change shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
