---
- name: Install Docker
  become: yes
  package:
    name:
      - docker
      - docker-compose

- name: Add user to 'docker' group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker

- name: Enable and start 'docker' service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started
